// TODO (pendiente, no urgente): varias paradas heredan una desc muy pobre del KMZ original
// (p.ej. "Asakusa" solo dice "barrio"). Pendiente pasarlas y escribir una frase útil para cada una.

// Config: qué placemark (por nombre EXACTO del KML) va en qué día, y en qué orden.
// kind: 'visit' (parada turística) | 'info' (vuelo/hotel/estación, no cuenta como visita)
// durOverride en minutos; si no se da, se infiere por palabra clave del nombre/desc.
// transit + transitMin: cuando el salto a la siguiente parada es largo (>20 min andando) y existe
// alternativa de transporte público razonable, se describe aquí y se usa transitMin para el reloj del día.
// dayStartTime: hora aproximada (HH:MM) en la que arranca la primera parada del día — de ahí se calculan
// en cascada las horas estimadas de llegada a cada parada siguiente.

// Lugares que NO estaban en el KMZ pero pidió el usuario explícitamente (destinos "ancla" confirmados
// por los vuelos/reservas). Coordenadas aproximadas a partir de conocimiento general del lugar.
const manualPlaces = [
  // Recordatorios de takkyubin — paradas virtuales (duración 0, kind:'info') en la ubicación del hotel correspondiente.
  { name: 'Takkyubin: avisar al hotel (envío a Kioto)', desc: 'Preguntad en recepción si el hotel ofrece servicio de takkyubin, para confirmarlo cuanto antes.', lat: 35.6972128, lon: 139.810939 },
  { name: 'Takkyubin: preparar bolsa pequeña (envío a Kioto)', desc: 'Preparad esta noche lo que necesitéis para los próximos 3 días (Kanazawa, Shirakawa-go, Takayama) en la mochila o bolsa de viaje.', lat: 35.6972128, lon: 139.810939 },
  { name: 'Takkyubin: entregar maleta (envío a Kioto)', desc: 'Entregad la maleta grande en recepción para el envío por takkyubin.', lat: 35.6972128, lon: 139.810939 },
  { name: 'Takkyubin: avisar al hotel (envío a Osaka)', desc: 'Preguntad en recepción si el hotel ofrece servicio de takkyubin, para confirmarlo cuanto antes.', lat: 35.0006295, lon: 135.7578639 },
  { name: 'Takkyubin: preparar bolsa pequeña (envío a Osaka)', desc: 'Preparad esta noche lo que necesitéis para mañana (Nara y el traslado a Osaka) en la mochila o bolsa de viaje.', lat: 35.0006295, lon: 135.7578639 },
  { name: 'Takkyubin: entregar maleta (envío a Osaka)', desc: 'Entregad la maleta grande en recepción para el envío por takkyubin.', lat: 35.0006295, lon: 135.7578639 },
  { name: 'Shibuya Sky', desc: 'Mirador al aire libre en lo alto del Shibuya Scramble Square, justo encima de la estación — vistas de 360° sobre el cruce de Shibuya.', lat: 35.6590, lon: 139.7016 },
  {
    name: 'Shugakuin Imperial Villa',
    desc: 'Villa imperial del siglo XVII en las colinas de Kioto, con tres jardines de paseo y vistas a las montañas. Visita guiada de ~1h20, solo con reserva previa (como el Palacio Sento).<br>A favor:<br>• Un estilo de jardín distinto a todo lo demás del viaje.<br>• Famosa por el otoño — encaja con las fechas del viaje.<br>• Una de las mejores vistas de Kioto, desde el Jardín Alto.',
    lat: 35.0429, lon: 135.8083,
  },
  { name: 'Palacio Imperial de Kioto (Gosho)', desc: 'Antigua residencia oficial de la familia imperial hasta el traslado a Tokio en 1869, dentro del mismo Parque Imperial (Kyoto Gyoen) que el Palacio Sento, unos minutos al norte. Visita guiada, solo con reserva previa en la Agencia de la Casa Imperial (Kunaicho).', lat: 35.0254, lon: 135.7622 },
  // Nara — no estaban en el KMZ, pedidos explícitamente
  { name: 'Nigatsu-dō', desc: 'Sala en lo alto de la colina de Tōdai-ji con un gran balcón de madera y vistas panorámicas sobre Nara. Entrada gratuita.', lat: 34.6897, lon: 135.8446 },
  { name: 'Kamaiki (Udon)', desc: 'Udon estilo Sanuki muy famoso (en la Guía Michelin), con los fideos cortados a mano cada mañana. Solo efectivo.', lat: 34.6829, lon: 135.8292 },
  { name: 'Higashimuki Shopping Street', desc: 'Galería comercial cubierta junto a la estación Kintetsu-Nara, con tiendas de recuerdos y comida.', lat: 34.6836, lon: 135.8290 },
  { name: 'Monte Wakakusa', desc: 'Colina de hierba de ~340 m junto al parque de Nara, con vistas de toda la ciudad. Entrada ¥150.', lat: 34.6883, lon: 135.8500 },
  { name: 'Estación Kintetsu-Nara', desc: 'Estación de la línea Kintetsu, mucho más cercana al parque de Nara que la JR Nara.', lat: 34.6839, lon: 135.8283 },
  { name: 'Arashiyama Yoshimura', desc: 'Soba artesanal con vistas al puente Togetsukyō y las montañas de Arashiyama, a un paso de Tenryu-ji y el bosque de bambú.', lat: 35.0100, lon: 135.6780 },
  { name: 'Kenrokuen', desc: 'Uno de los tres jardines (Nihon Sanmei) más famosos de Japón, junto al Castillo de Kanazawa.', lat: 36.5613, lon: 136.6625 },
  { name: 'Nagamachi', desc: 'Antiguo barrio de samuráis, calles empedradas con muros de barro y canales.', lat: 36.5645, lon: 136.6536 },
  { name: 'Higashi Chaya', desc: 'El mayor de los distritos de casas de té (geishas) de Kanazawa, con pan de oro en las tiendas.', lat: 36.5716, lon: 136.6636 },
  { name: 'Kazuemachi', desc: 'Distrito de casas de té más pequeño y tranquilo, a orillas del río Asano.', lat: 36.5687, lon: 136.6597 },
  { name: 'Mercado Omicho', desc: 'El mercado de abastos de Kanazawa, apodado "la cocina de la ciudad", con casi 300 años de historia y 180 puestos de ostras, sushi fresco, fruta, pescado, carne y setas.', lat: 36.5714, lon: 136.6547 },
  { name: 'Ginkaku-ji', desc: 'El "Pabellón de Plata", templo zen del siglo XV que marca la entrada norte del Camino del Filósofo. Patrimonio Unesco.', lat: 35.0270, lon: 135.7981 },
  { name: 'Sumida', desc: 'Barrio a orillas del río, justo al cruzar el Puente Azuma desde Asakusa, a los pies del Skytree.', lat: 35.7100, lon: 139.8050 },
  { name: 'Explanada y Puente Nijūbashi', desc: 'La vista más icónica del Palacio Imperial: el puente Nijūbashi y la Fushimi Yagura al fondo, desde la explanada Kōkyo Gaien (siempre accesible, sin horario). El Jardín Este del palacio cierra los lunes y viernes.', lat: 35.6825, lon: 139.7528 },
  { name: 'Estación de Tokio (Marunouchi)', desc: 'Fachada histórica de ladrillo rojo de 1914, desde donde sale el Shinkansen a Kanazawa.', lat: 35.6812, lon: 139.7671 },
  // Ginza — no estaban en el KMZ, pedidos explícitamente
  { name: 'Avenida Chuo-dori', desc: 'La calle principal de Ginza. Los domingos de 12:00 a 17:00 se corta al tráfico (hokosha tengoku) y se llena de gente paseando por el centro de la calzada.', lat: 35.6714, lon: 139.7660 },
  { name: 'Seiko House Ginza (Wako)', desc: 'El edificio con la torre del reloj más icónico de Ginza, en la esquina del cruce de Ginza 4-chōme.', lat: 35.6716, lon: 139.7658 },
  { name: 'Ginza Place', desc: 'Edificio de diseño en celosía blanca, frente a Wako, con Nissan y Canon.', lat: 35.6711, lon: 139.7658 },
  { name: 'Almacenes Mitsukoshi Ginza', desc: 'Grandes almacenes centenarios; en la azotea está la estatua Ginza Shusse Jizoson (da buena suerte), y en el sótano hay puestos de comida (depachika).', lat: 35.6714, lon: 139.7664 },
  { name: 'Itoya Ginza', desc: 'La papelería más famosa del mundo — varias plantas de material de escritura y papel de diseño.', lat: 35.6739, lon: 139.7651 },
  { name: 'Pokémon Center Tokyo DX', desc: 'La tienda oficial de Pokémon más grande de Tokio, dentro del centro comercial Nihombashi Takashimaya S.C.', lat: 35.6835, lon: 139.7745 },
  { name: 'Matsuya Ginza', desc: 'Grandes almacenes en plena Chuo-dori, muy cerca de Itoya.', lat: 35.6735, lon: 139.7655 },
  { name: 'Ginza Six', desc: 'El centro comercial más grande de Ginza, con marcas de lujo y una gran librería (Tsutaya).', lat: 35.6693, lon: 139.7627 },
  // Shirakawa-go — no estaban en el KMZ, pedidos explícitamente
  { name: 'Mirador Shiroyama', desc: 'Mirador en la colina sur del valle, con la vista panorámica más famosa de Shirakawa-go.', lat: 36.2543, lon: 136.9033 },
  { name: 'Casa Museo Wada', desc: 'La casa gasshō-zukuri más grande y visitada del pueblo, Bien Cultural Importante de Japón.', lat: 36.2588, lon: 136.9064 },
  { name: 'Kanda y Nagase', desc: 'Dos casas gasshō-zukuri más, abiertas como museo, muy cerca de la Casa Wada.', lat: 36.2566, lon: 136.9070 },
  { name: 'Templo Myozenji y Santuario Shirakawa Hachiman', desc: 'El templo Myozen-ji (con museo etnográfico) y el santuario sintoísta que da nombre al Festival Doburoku del pueblo.', lat: 36.2560, lon: 136.9072 },
  { name: 'Puente Colgante Deai', desc: 'Puente colgante sobre el río Shogawa, la entrada peatonal clásica al pueblo.', lat: 36.2610, lon: 136.9038 },
  { name: 'Las Tres Casas de Shirakawago', desc: 'El mirador de las tres casas gasshō-zukuri alineadas frente al arrozal.', lat: 36.2580, lon: 136.9055 },
  // Takayama — no estaban en el KMZ, pedidos explícitamente
  { name: 'Sanmachi Suji (Casco Antiguo)', desc: 'Las calles Ichino-machi, Ni-no-machi y San-no-machi, con casas de comerciantes del periodo Edo convertidas en museos, galerías, tiendas de artesanía, destilerías de sake y cafeterías.', lat: 36.1418, lon: 137.2533 },
  { name: 'Takayama Jinya', desc: 'Antigua sede del gobierno local en el periodo Edo, junto al río Miyagawa — el único palacio de gobierno de esa época que se conserva en pie en todo Japón.', lat: 36.1404, lon: 137.2513 },
  { name: 'Kusakabe Mingeikan', desc: 'Casa-museo de la familia Kusakabe, mercaderes de sake y aceite en el periodo Edo.', lat: 36.1432, lon: 137.2531 },
  { name: 'Yoshijima-ke', desc: 'Casa histórica de la familia Yoshijima, ejemplo de arquitectura tradicional de comerciantes.', lat: 36.1431, lon: 137.2529 },
  { name: 'Hida Minzoku Kokokan', desc: 'Museo arqueológico de Hida, en una antigua residencia samurái junto al Shiroyama.', lat: 36.1394, lon: 137.2554 },
  { name: 'Hirata Kinenkan', desc: 'Museo de artesanía en una antigua tienda de velas y aceite de Kamisannomachi.', lat: 36.1417, lon: 137.2538 },
  { name: 'Fujii Bijutsu Mingeikan', desc: 'Galería de arte y artesanía tradicional junto a Kusakabe Mingeikan.', lat: 36.1433, lon: 137.2534 },
  { name: 'Templo Hida Kokubunji', desc: 'El templo más antiguo de Takayama, con una pagoda de tres pisos y un ginkgo milenario.', lat: 36.1421, lon: 137.2495 },
  { name: 'Asaichi', desc: 'Mercados matinales junto al río Miyagawa: verduras, encurtidos, artesanía y saru-bobo.', lat: 36.1442, lon: 137.2521 },
  { name: 'Santuario Sakurayama Hachimangu', desc: 'Santuario sintoísta al norte del casco antiguo; alberga el museo de los carros del festival de Takayama.', lat: 36.1481, lon: 137.2500 },
  { name: 'Teramachi', desc: 'Paseo por el barrio de templos en la ladera este, junto al parque Shiroyama (antiguo castillo de Takayama).', lat: 36.1400, lon: 137.2565 },
  { name: 'Parque Shiroyama', desc: 'Antiguo enclave del castillo de Takayama, hoy parque y mirador sobre la ciudad.', lat: 36.1373, lon: 137.2580 },
];

// Comida sugerida en Takayama que no estaba en la capa "comer en japon" del KMZ.
const manualFood = [
  { name: 'Ajikura Tengoku', desc: 'Buñuelos de carne Hida (estilo takoyaki), donburi y nigiri de Hida wagyu.', lat: 36.1424, lon: 137.2539 },
  { name: 'Aji no Yohei', desc: 'Hoba-miso y chuka soba, cocina local de Hida.', lat: 36.1419, lon: 137.2537 },
  { name: 'Funasaka Sake Brewery', desc: 'Bodega de sake tradicional en Kamisannomachi, con cata.', lat: 36.1413, lon: 137.2536, notMeal: true },
];

const CITY_COLORS = {
  Tokio: '#b8442a',
  'Kanazawa-Takayama': '#33475a',
  Kioto: '#8a6d1f',
  Osaka: '#6b5b95',
};

const days = [
  // ---------------- TOKIO ----------------
  {
    date: '2026-10-28', city: 'Tokio', locationLabel: 'Tokyo', title: 'Llegada, Asakusa y Sumida',
    kind: 'city', dayStartTime: '12:50',
    stops: [
      { name: 'Haneda airport', kind: 'info', note: 'Vuelo de llegada: HND-TOKYO, miércoles 28 oct 12:50.', transit: 'Keikyu Airport Line + Toei Asakusa Line (servicio directo, sin trasbordo) Haneda → Asakusa, ~45 min.', transitMin: 45 },
      { name: 'Hotel Tokyo', kind: 'info', note: 'Dejar las maletas en el Hotel Tobu Levant — el check-in suele ser a partir de las 15:00, puede que solo os guarden el equipaje hasta la noche.' },
      { name: 'Takkyubin: avisar al hotel (envío a Kioto)', kind: 'info', note: 'Necesitaréis el servicio el 2 nov, destino Hotel Resol Shijo Muromachi (Kioto), entrega prevista el 5 nov.', transit: 'Metro Toei Asakusa Line Oshiage → Asakusa, 1 parada (~5 min) — o ~30 min andando.', transitMin: 12 },
      { name: 'Kuramae', kind: 'visit', transit: 'Toei Asakusa Line Kuramae → Asakusa, 1 parada (~3 min).', transitMin: 10 },
      { name: 'Asakusa', kind: 'visit' },
      { name: 'Sensō-ji', kind: 'visit' },
      { name: 'Calle Comercial Nakamise', kind: 'visit' },
      { name: 'Calle Comercial Shin-Nakamise', kind: 'visit' },
      { name: 'Centro de Información Turística y Cultural de Asakusa', kind: 'visit' },
      { name: 'Hoppy Street', kind: 'visit' },
      { name: 'Puente Azuma', kind: 'visit' },
      { name: 'Sumida', kind: 'visit', durOverride: 20, note: 'Vistas del Skytree desde el parque, sin subir — decidimos que no merecía la pena por el precio y por ir de noche (brillos en el cristal); ya se ve Tokio desde arriba en el avión.', transit: 'Metro Tobu/Toei Oshiage → hotel, 1 parada o 15 min andando.', transitMin: 15 },
      { name: 'Hotel Tokyo', kind: 'info' },
    ],
  },
  {
    date: '2026-10-29', city: 'Tokio', locationLabel: 'Tokyo', title: 'Ueno, Yanaka y Akihabara',
    kind: 'city', dayStartTime: '07:30',
    stops: [
      { name: 'Hotel Tokyo', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.', transit: 'Metro Toei Asakusa Oshiage → Asakusa (~5 min) + Ginza Line Asakusa → Ueno (~5 min) — o ~70 min andando.', transitMin: 20 },
      { name: 'Parque de Ueno', kind: 'visit' },
      {
        name: 'Museo Nacional de Tokio', kind: 'visit', durOverride: 90,
        note: 'Horario: martes a domingo 09:30-17:00 (viernes y sábados hasta las 21:00), lunes cerrado. Entrada 1.000 yenes.',
      },
      {
        name: 'Ueno Zoo', kind: 'visit', durOverride: 90, optional: true,
        note: 'Opcional — ya no tiene los pandas gigantes desde enero de 2026. Horario 9:30-17:00, cierra los lunes.',
      },
      { name: 'Ameyoko market', kind: 'visit', durOverride: 55, mealAfter: 'lunch', transit: 'JR/Keisei Ueno → Nippori (~5 min) + 10 min andando a Yanaka.', transitMin: 15 },
      { name: 'Yanaka', kind: 'visit', durOverride: 95, note: 'Callejeo tranquilo de casas bajas y templos — dedicadle tiempo sin prisa, es de los rincones con más encanto de Tokio.', transit: 'JR Yamanote/Keihin-Tōhoku Nippori → Komagome (~10 min) + 7 min andando a Rikugien.', transitMin: 17 },
      { name: 'Jardín Rikugien', kind: 'visit', durOverride: 60, transit: 'JR Yamanote Line Komagome → Akihabara, ~15 min.', transitMin: 15 },
      { name: 'Akihabara', kind: 'visit', durOverride: 75 },
      { name: 'TAITO Station Akihabara', kind: 'visit', durOverride: 55, mealAfter: 'dinner', transit: 'Metro Hanzomon Line directo Akihabara → Oshiage, ~10 min — o ~60 min andando.', transitMin: 15 },
      { name: 'Hotel Tokyo', kind: 'info' },
    ],
  },
  {
    date: '2026-10-30', city: 'Tokio', locationLabel: 'Tokyo', title: 'Shibuya, Shinjuku, Kabukichō y Okubo',
    kind: 'city', dayStartTime: '07:00',
    stops: [
      { name: 'Hotel Tokyo', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.', transit: 'Metro Hanzomon Line Oshiage → Omotesando (~25 min) + 5 min andando a Meiji Jingū.', transitMin: 30 },
      { name: 'Santuario Meiji', kind: 'visit', durOverride: 45 },
      { name: 'Parque Yoyogi', kind: 'visit' },
      { name: 'Calle Takeshita', kind: 'visit' },
      { name: 'Omote-Sando Avenue', kind: 'visit', note: 'Si os sobran ~20 min: Paradise Vintage está a 2 min andando y AMORE Vintage Aoyama a 5 min — ropa vintage.' },
      { name: 'Shibuya Crossing', kind: 'visit', durOverride: 15 },
      { name: 'Hachiko Statue', kind: 'visit', durOverride: 10 },
      { name: 'Shibuya Sky', kind: 'visit', durOverride: 60, mealAfter: 'lunch', note: 'Reservad hora con antelación online — se agotan franjas los fines de semana.' },
      { name: 'Calle Central de Shibuya', kind: 'visit', note: 'Si os sobran ~20 min: BRAND OFF Shibuya está aquí mismo y MEGA Don Quijote a 3 min — vintage y outlet turístico.' },
      { name: 'Dogenzaka', kind: 'visit' },
      { name: 'Shibuya Nonbei Yokocho', kind: 'visit', transit: 'JR Yamanote Line Shibuya → Shinjuku, ~7 min.', transitMin: 15 },
      { name: 'Shinjuku', kind: 'visit', durOverride: 0 },
      { name: 'Mirador del Gobierno Metropolitano de Tokio', kind: 'visit', durOverride: 40 },
      { name: 'Park Hyatt Tokyo', kind: 'visit', durOverride: 15, note: 'A 5 min andando del mirador.' },
      { name: 'Omoide Yokochō', kind: 'visit', durOverride: 60 },
      { name: 'Shinjuku Ni-chōme', kind: 'visit', durOverride: 30 },
      { name: 'Kabukichō', kind: 'visit' },
      { name: 'Tokyu Kabukicho Tower', kind: 'visit', mealAfter: 'dinner', transit: 'JR Yamanote/Sōbu Line Shinjuku → Shin-Ōkubo, ~5 min.', transitMin: 12 },
      {
        name: 'Okubo', kind: 'visit', durOverride: 45, optional: true,
        note: 'Opcional, dejadlo para el final del día si os queda tiempo y energía.',
        transit: 'Vuelta en JR Yamanote/Sōbu a Shinjuku (~5 min) + Toei Oedo Line a Kuramae (~25 min) + Toei Asakusa Line a Oshiage (~5 min).', transitMin: 45,
      },
      { name: 'Hotel Tokyo', kind: 'info' },
    ],
  },
  {
    date: '2026-10-31', city: 'Tokio', locationLabel: 'Tokyo', title: 'Excursión a Kamakura',
    kind: 'daytrip', dayStartTime: '07:00',
    optional: true, altGroup: 'day4', altLabel: 'A',
    altNote: 'Elegid <b>4A (Kamakura)</b> o <b>4B (Hakone)</b> la mañana de antes, según el tiempo — Kamakura (templos y costa) funciona con cualquier tiempo; Hakone (montaña y volcán) solo compensa con cielo despejado para ver el Fuji.',
    travelNote: 'Desde el hotel, camino a Kinshichō Station (a pocos minutos). Sōbu Line (Rapid) dirección Zushi, que continúa automáticamente como Yokosuka Line (mismo tren, sin trasbordo) hasta Kamakura Station, ~1h en total. Dentro de Kamakura, el bus o el tren local Enoden conecta el Daibutsu con Hase y la costa si os sobra tiempo.',
    stops: [
      { name: 'Hotel Tokyo', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.', transit: 'Caminando a Kinshichō Station (pocos minutos) + Sōbu Line (Rapid) dirección Zushi, que continúa como Yokosuka Line (mismo tren, sin trasbordo) → Kamakura Station, ~1h en total.', transitMin: 70 },
      { name: 'Kamakura', kind: 'visit', durOverride: 0 },
      { name: 'Templo Kotoku-in', kind: 'visit', durOverride: 40, mealAfter: 'lunch', transit: 'Enoden Hase → Kamakura Station (~15 min) + bus/taxi a Hokoku-ji (~10 min).', transitMin: 25 },
      { name: 'Templo Hokoku-ji', kind: 'visit', durOverride: 40, transit: 'Bus Keikyu de vuelta a Kamakura Station (~10 min) + 10 min andando a Tsurugaoka.', transitMin: 18 },
      { name: 'Tsurugaoka Hachiman-gū', kind: 'visit', durOverride: 40 },
      { name: 'Komachi Street', kind: 'visit', durOverride: 45, mealAfter: 'dinner', note: 'Probad la croqueta de pan de curry (curry pan), típica de la calle.', transit: 'JR Yokosuka Line Kamakura → Tokio/Shinagawa (~55 min-1h) + metro Asakusa Line a Oshiage (~15 min).', transitMin: 75 },
      { name: 'Hotel Tokyo', kind: 'info' },
    ],
  },
  {
    date: '2026-10-31', city: 'Tokio', locationLabel: 'Tokyo', title: 'Excursión a Hakone',
    kind: 'daytrip', dayStartTime: '07:00',
    optional: true, altGroup: 'day4', altLabel: 'B',
    altNote: 'Elegid <b>4B (Hakone)</b> o <b>4A (Kamakura)</b> la mañana de antes, según el tiempo — Hakone solo compensa con cielo despejado, para ver el Fuji desde el teleférico y el lago Ashi. Si está nublado, mejor Kamakura.',
    travelNote: 'Odakyu Romancecar directo Shinjuku → Hakone-Yumoto (~1h25-1h35). Sacad el Hakone Freepass en la estación: incluye el tren de montaña, el cable car, el teleférico (ropeway) y el barco pirata del lago Ashi, todo lo necesario para el circuito del día.',
    stops: [
      { name: 'Hotel Tokyo', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel, con tiempo de sobra para el Romancecar.', transit: 'Metro Hanzomon Line Oshiage → Shinjuku-sanchōme (~30 min) + Odakyu Romancecar directo Shinjuku → Hakone-Yumoto (~1h25-1h35).', transitMin: 130 },
      { name: 'Hakone', kind: 'visit', durOverride: 10, note: 'Sacad el Hakone Freepass en la estación antes de moveros — incluye todo el transporte del día.', transit: 'Hakone Tozan Railway Hakone-Yumoto → Gora, ~40 min.', transitMin: 40 },
      { name: 'Museo al Aire Libre de Hakone', kind: 'visit', durOverride: 90, transit: 'Cable car Gora → Sōunzan (~10 min) + teleférico (ropeway) Sōunzan → Owakudani, ~20 min en total.', transitMin: 20 },
      { name: 'Teleférico de Hakone', kind: 'visit', durOverride: 15 },
      { name: 'Owakudani', kind: 'visit', durOverride: 45, note: 'Probad un kuro-tamago — dicen que alarga la vida 7 años. Hay soba/curry en la zona si no habéis comido.', transit: 'Teleférico Owakudani → Togendai (~15 min) + barco pirata cruzando el lago Ashi a Hakone-machi (~30 min).', transitMin: 45 },
      { name: 'Santuario Hakone', kind: 'visit', durOverride: 40, transit: 'Bus Hakone Tozan Hakone-machi → Hakone-Yumoto (~30 min) + Odakyu Romancecar Hakone-Yumoto → Shinjuku (~1h25-1h35) + Metro Hanzomon Line a Oshiage (~30 min).', transitMin: 150 },
      { name: 'Hotel Tokyo', kind: 'info', note: 'De camino, el shotengai de Hakone-Yumoto tiene puestos de soba y comida si preferís cenar antes de subir al tren.' },
    ],
  },
  {
    date: '2026-11-01', city: 'Tokio', locationLabel: 'Tokyo', title: 'Ginza',
    kind: 'city', dayStartTime: '11:30',
    travelNote: 'Domingo: la Avenida Chuo-dori (la calle principal de Ginza) se corta al tráfico de 12:00 a 17:00 (hokosha tengoku) y se convierte en un paseo peatonal gigante — por eso esta ruta encaja mejor en domingo que en otro día.',
    stops: [
      { name: 'Hotel Tokyo', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.', transit: 'Metro Toei Asakusa Line Oshiage → Higashi-Ginza (~20 min) — o ~85 min andando.', transitMin: 25 },
      { name: 'Matsuya Ginza', kind: 'visit', durOverride: 45 },
      { name: 'Itoya Ginza', kind: 'visit', durOverride: 35, mealAfter: 'lunch', transit: 'Metro Ginza Line Ginza → Nihombashi, ~5 min en total — o ~30 min andando.', transitMin: 10 },
      { name: 'Pokémon Center Tokyo DX', kind: 'visit', durOverride: 30, transit: 'Metro Ginza Line Nihombashi → Ginza, ~5 min en total — o ~25 min andando.', transitMin: 10 },
      { name: 'Avenida Chuo-dori', kind: 'visit', durOverride: 30 },
      { name: 'Seiko House Ginza (Wako)', kind: 'visit', durOverride: 20 },
      { name: 'Ginza Place', kind: 'visit', durOverride: 15 },
      { name: 'Almacenes Mitsukoshi Ginza', kind: 'visit', durOverride: 40 },
      { name: 'Ginza', kind: 'visit', durOverride: 75, note: 'Buen rato para callejear sin rumbo por las bocacalles.' },
      { name: 'Ginza Six', kind: 'visit', durOverride: 80, mealAfter: 'dinner', transit: 'Metro Toei Asakusa Line Higashi-Ginza → Asakusa, ~15 min — o ~90 min andando.', transitMin: 20 },
      { name: 'Hotel Tokyo', kind: 'info' },
      { name: 'Takkyubin: preparar bolsa pequeña (envío a Kioto)', kind: 'info', note: 'Mañana (2 nov) se entrega la maleta grande en el hotel para el takkyubin a Kioto.' },
    ],
  },
  {
    date: '2026-11-02', city: 'Tokio', locationLabel: 'Kanazawa', title: 'Tokyo → Kanazawa',
    kind: 'travel', dayStartTime: '07:30',
    travelNote: 'Tokio tiene mucho más que ver que Kanazawa, así que aprovechamos la mañana antes del Shinkansen. Hokuriku "Kagayaki" Tokio → Kanazawa (~2h30, asiento reservado recomendado). Antes de salir del hotel, entregad la maleta grande en recepción para enviarla por takkyubin directa al hotel de Kioto (llegada programada para el 5 nov) — así hacéis Kanazawa, Shirakawa-go y Takayama solo con la mochila.',
    stops: [
      { name: 'Hotel Tokyo', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno rápido en el hotel (o saltadlo si vais a comer en Toyosu).' },
      { name: 'Takkyubin: entregar maleta (envío a Kioto)', kind: 'info', note: 'Destino: Hotel Resol Shijo Muromachi, Kioto. Entrega prevista: 5 nov.', transit: 'Metro Yurikamome/Toei Oedo a Toyosu, ~25-30 min.', transitMin: 30 },
      {
        name: 'Toyosu Senkyaku Banrai', kind: 'visit', durOverride: 45, optional: true,
        note: 'Opcional — solo si salís al amanecer, os quita tiempo para el Palacio Imperial. Alternativa: ir directamente a la Estación de Tokio para llegar antes a Kanazawa — la mejor opción si ya habéis hecho las compras que queríais.',
        transit: 'Metro Yurikamome Toyosu → Tokyo Station, ~20 min — o ~85 min andando.', transitMin: 20,
      },
      {
        name: 'Explanada y Puente Nijūbashi', kind: 'visit', durOverride: 35, optional: true,
        note: 'Opcional — el Palacio Imperial no merece mucho la pena, es más para rellenar tiempo antes del Shinkansen. Alternativas: ir de compras a lo que no hayáis podido comprar todavía, o iros directos a la Estación de Tokio para llegar antes a Kanazawa si ya habéis comprado todo lo que queríais.',
      },
      { name: 'Estación de Tokio (Marunouchi)', kind: 'visit', durOverride: 20, transit: 'Shinkansen Hokuriku "Kagayaki" Tokio → Kanazawa, ~2h30.', transitMin: 150 },
      {
        name: 'Estación de Kanazawa', kind: 'visit', durOverride: 15,
        note: 'Vedla antes de seguir — están justo a la salida.',
      },
      { name: 'Tsuzumi-mon Gate', kind: 'visit', durOverride: 10, transit: 'Bus turístico Kanazawa Loop Bus, ~10 min hasta la parada más cercana al hotel — o ~20 min andando.', transitMin: 10 },
      { name: 'Hotel Kanazawa', kind: 'info', note: 'Check-in en el Hotel Tokyu Stay Kanazawa. Lleváis solo la mochila — la maleta grande va directa a Kioto, enviada desde Tokio.', transit: '5 min andando al mercado.', transitMin: 5 },
      { name: 'Mercado Omicho', kind: 'meal', mealType: 'lunch', durOverride: 45 },
      { name: 'Nagamachi', kind: 'visit', durOverride: 60 },
      { name: 'Kenrokuen', kind: 'visit', durOverride: 100, note: 'En temporada de momiji (otoño), todo rojo.' },
      { name: 'Kazuemachi', kind: 'visit', durOverride: 45 },
      { name: 'Higashi Chaya', kind: 'visit', durOverride: 60, mealAfter: 'dinner' },
      { name: 'Hotel Kanazawa', kind: 'info' },
    ],
  },
  // ---------------- KANAZAWA / TAKAYAMA ----------------
  {
    date: '2026-11-03', city: 'Kanazawa-Takayama', locationLabel: 'Shirakawa-go', title: 'Kanazawa → Shirakawa-go → Takayama',
    kind: 'travel', dayStartTime: '07:20',
    travelNote: 'Bus Nohi/Hokutetsu Kanazawa (sale 08:10) → Shirakawa-go Ogimachi (llega 09:25) y después bus Nohi Shirakawa-go (sale 13:30) → Takayama (llega 14:20) — horarios reales confirmados en japanbusonline.com, con margen de sobra para ver Shirakawa-go sin prisas (la tarde en Takayama queda libre, así que no pasa nada por llegar más tarde). Las reservas solo se abren 1 mes antes del viaje (para el 3 nov, a partir del 3 oct): volved a la web esa fecha para completar la compra, se llenan en temporada de otoño.',
    stops: [
      { name: 'Hotel Kanazawa', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel — solo la mochila, check-out rápido.', transit: '10 min andando a la terminal (Kanazawa Sta. West Exit, parada nº4) + Bus Nohi/Hokutetsu, sale 08:10 → Shirakawa-go (Ogimachi), llega 09:25.', transitMin: 95 },
      { name: 'Shirakawa', kind: 'visit', durOverride: 5, note: 'Con el bus de las 13:30 de vuelta, hay tiempo de sobra para verlo con calma.' },
      { name: 'Mirador Shiroyama', kind: 'visit', durOverride: 30, transit: 'Shuttle Shiroyama Line hasta el mirador (ida, ¥200), ~5 min.', transitMin: 8 },
      { name: 'Casa Museo Wada', kind: 'visit', durOverride: 30 },
      { name: 'Kanda y Nagase', kind: 'visit', durOverride: 25 },
      { name: 'Templo Myozenji y Santuario Shirakawa Hachiman', kind: 'visit', durOverride: 25 },
      { name: 'Puente Colgante Deai', kind: 'visit', durOverride: 15 },
      { name: 'Las Tres Casas de Shirakawago', kind: 'visit', durOverride: 20, note: 'La foto más famosa de Shirakawago.', transit: '5 min andando a la terminal de autobuses + Bus Nohi, sale 13:30 → Takayama, llega 14:20.', transitMin: 60 },
      { name: 'Hotel Takayama', kind: 'info', note: 'Check-in en el Hotel Hida Takayama Green.' },
      { name: 'Takayama Old Town', kind: 'visit', durOverride: 75, note: 'Cenar carne Hida wagyu en Hidagyu Maruaki o Ajikura Tengoku (buñuelos, donburi o nigiri de Hida wagyu).' },
      { name: 'Hotel Takayama', kind: 'info' },
    ],
  },
  {
    date: '2026-11-04', city: 'Kanazawa-Takayama', locationLabel: 'Takayama', title: 'Takayama: casco antiguo y museos',
    kind: 'city', dayStartTime: '07:00',
    stops: [
      { name: 'Hotel Takayama', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.' },
      { name: 'Asaichi', kind: 'visit', durOverride: 45, note: 'Mercados matinales junto al río — cierran sobre el mediodía, por eso van primero. Buen sitio para comprar un saru-bobo.' },
      { name: 'Takayama Jinya', kind: 'visit', durOverride: 35, note: 'Entrada: 440 yenes.' },
      { name: 'Santuario Sakurayama Hachimangu', kind: 'visit', durOverride: 25 },
      { name: 'Kusakabe Mingeikan', kind: 'visit', durOverride: 30 },
      { name: 'Yoshijima-ke', kind: 'visit', durOverride: 25 },
      { name: 'Fujii Bijutsu Mingeikan', kind: 'visit', durOverride: 20 },
      { name: 'Sanmachi Suji (Casco Antiguo)', kind: 'visit', durOverride: 40 },
      { name: 'Hirata Kinenkan', kind: 'visit', durOverride: 25 },
      { name: 'Templo Hida Kokubunji', kind: 'visit', durOverride: 25, mealAfter: 'lunch' },
      { name: 'Teramachi', kind: 'visit', durOverride: 40 },
      { name: 'Parque Shiroyama', kind: 'visit', durOverride: 35 },
      { name: 'Hida Minzoku Kokokan', kind: 'visit', durOverride: 50 },
      { name: 'Takayama Shōwa-kan Museum', kind: 'visit', durOverride: 85, transit: 'Bus turístico Sarubobo, Takayama Station → Hida no Sato, ~10 min.', transitMin: 15 },
      {
        name: 'Hida no Sato Folk Village Museum', kind: 'visit', durOverride: 90, optional: true,
        note: 'Opcional — réplica de pueblo con casas gasshō-zukuri; si ya habéis visto Shirakawa-go en persona, os la podéis saltar.',
        transit: 'Bus Sarubobo de vuelta hacia el centro, parada cercana al hotel, ~10 min.', transitMin: 12,
      },
      { name: 'Hotel Takayama', kind: 'info', mealAfter: 'dinner' },
    ],
  },
  {
    date: '2026-11-05', city: 'Kanazawa-Takayama', locationLabel: 'Takayama', title: 'Takayama → Kioto (Magome-juku)',
    kind: 'travel', dayStartTime: '07:30',
    optional: true, altGroup: 'day9', altLabel: 'A',
    altNote: 'Elegid <b>9A (Magome-juku)</b> o <b>9B (directo)</b> — 9A añade ~2h de trenes/bus para ver el pueblo postal de Magome-juku de camino; 9B llega a Kioto sobre el mediodía con toda la tarde libre para más turismo.',
    travelNote: 'Limited Express "Hida" Takayama → Nagoya (~2h20) + JR línea Chūō a Nakatsugawa (~50 min) + bus a Magome-juku (~30 min); a la vuelta, bus a Nakatsugawa (~30 min) + JR línea Chūō a Nagoya (~50 min) + Shinkansen Tōkaidō a Kioto (~35-45 min). No hay bus directo Takayama-Nakatsugawa, hay que bajar hasta Nagoya y volver a subir en la línea JR Chūō.',
    stops: [
      { name: 'Hotel Takayama', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel. Seguís viajando solo con la mochila.', transit: 'Camino a la estación (~10 min) + Limited Express "Hida" a Nagoya (~2h20) + JR línea Chūō a Nakatsugawa (~50 min).', transitMin: 200 },
      { name: 'Nakatsugawa Station', kind: 'visit', durOverride: 10, transit: 'Bus local Nakatsugawa → Magome-juku, ~30 min.', transitMin: 30 },
      { name: 'Magome-juku', kind: 'visit', durOverride: 90, note: 'Comer soba en Yoshimura Soba.', transit: 'Bus de vuelta a Nakatsugawa (~30 min) + JR línea Chūō a Nagoya (~50 min) + Shinkansen Tōkaidō a Kioto (~35-45 min).', transitMin: 125 },
      { name: 'Hotel Kyoto', kind: 'info', note: 'Check-in en el Hotel Resol Shijo Muromachi — la maleta grande, enviada por takkyubin desde Tokio el 2 nov, ya debería estar esperando.' },
      { name: 'Takkyubin: avisar al hotel (envío a Osaka)', kind: 'info', note: 'Necesitaréis el servicio el 8 nov, destino Hotel Keihan Tenmabashi Ekimae (Osaka), entrega prevista el 9 nov.' },
    ],
  },
  {
    date: '2026-11-05', city: 'Kanazawa-Takayama', locationLabel: 'Takayama', title: 'Takayama → Kioto (directo)',
    kind: 'travel', dayStartTime: '07:30',
    optional: true, altGroup: 'day9', altLabel: 'B',
    altNote: 'Elegid <b>9B (directo)</b> o <b>9A (Magome-juku)</b> — 9B llega a Kioto sobre el mediodía con toda la tarde libre para más turismo; 9A añade ~2h de trenes/bus para ver el pueblo postal de Magome-juku de camino.',
    travelNote: 'Limited Express "Hida" Takayama → Nagoya (~2h20) + Shinkansen Tōkaidō Nagoya → Kioto (~35-45 min), sin desvíos — el tramo más rápido posible. Llegada a Kioto sobre las 11:00, con toda la tarde libre: Higashi Hongan-ji y Nishi Hongan-ji nada más llegar, luego el Parque del Palacio Imperial de Kioto (con el tour guiado gratuito del Gosho a las 14:00) y por último el Castillo Nijō antes de cenar.',
    stops: [
      { name: 'Hotel Takayama', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel. Seguís viajando solo con la mochila.', transit: 'Camino a la estación (~10 min) + Limited Express "Hida" a Nagoya (~2h20) + Shinkansen Tōkaidō a Kioto (~35-45 min).', transitMin: 200 },
      { name: 'Templo Higashi Hongan-ji', kind: 'visit', durOverride: 30, note: 'Justo enfrente de la estación — ideal para visitarlo nada más llegar.' },
      { name: 'Men-ya Inoichi Hanare', kind: 'meal', mealType: 'lunch', durOverride: 45, note: 'Muy recomendado, incluso venden camisetas del restaurante. Quizá sea un poco pronto para comer — valorad sobre la marcha según el tiempo que llevéis, pero sin apurar demasiado: lo prioritario es no llegar tarde al tour reservado del Gosho a las 14:00.' },
      { name: 'Templo Nishi Hongan-ji', kind: 'visit', durOverride: 22, transit: 'Metro Karasuma Line Kyoto → Imadegawa (~11 min) + 5 min andando a la Puerta Seishomon — o ~65 min andando desde aquí.', transitMin: 20 },
      { name: 'Palacio Imperial de Kioto (Gosho)', kind: 'visit', durOverride: 50, note: 'Entrada por la Puerta Seishomon, sin necesidad de reserva previa. Tour guiado gratuito en inglés a las 10:00 y a las 14:00 (~50 min) — vamos al de las 14:00; llegad unos minutos antes para la entrada.', transit: 'Paseo dentro del parque hasta el Sento (5 min), con margen hasta el turno reservado.', transitMin: 40 },
      { name: 'Palacio Imperial Sento de Kioto', kind: 'visit', durOverride: 30, note: 'Solo con tour guiado obligatorio (no se puede ir por libre) — turno reservado a las 15:30, el único que encajaba tras el tour del Gosho a las 14:00.<br>Reserva confirmada: 2026-11-05 15:30, nº de permiso 611321403.<br>Aviso del permiso de visita: <a href="https://sankan.kunaicho.go.jp/permit/login?locale=en" target="_blank" rel="noopener">sankan.kunaicho.go.jp</a><br>App de audioguía (descargar antes): <a href="https://www.kunaicho.go.jp/en/visit/guide/app.html" target="_blank" rel="noopener">kunaicho.go.jp/en/visit/guide/app</a>' },
      { name: 'Santuario Shirakumo', kind: 'visit', durOverride: 15 },
      { name: 'Munakata Shrine', kind: 'visit', durOverride: 15 },
      { name: 'Santuario Itsukushima (interior del Parque del Palacio Imperial de Kioto)', kind: 'visit', durOverride: 15, transit: 'Metro Tozai Line Marutamachi → Nijōjō-mae (~10 min) + 5 min andando al castillo — o ~20 min andando directo.', transitMin: 15 },
      { name: 'Castillo Nijō', kind: 'visit', durOverride: 75, mealAfter: 'dinner' },
      { name: 'Hotel Kyoto', kind: 'info', note: 'Check-in en el Hotel Resol Shijo Muromachi — la maleta grande, enviada por takkyubin desde Tokio el 2 nov, ya debería estar esperando.' },
      { name: 'Takkyubin: avisar al hotel (envío a Osaka)', kind: 'info', note: 'Necesitaréis el servicio el 8 nov, destino Hotel Keihan Tenmabashi Ekimae (Osaka), entrega prevista el 9 nov.' },
    ],
  },
  // ---------------- KIOTO ----------------
  {
    date: '2026-11-06', city: 'Kioto', locationLabel: 'Kyoto', title: 'Higashiyama: Kiyomizu y Gion',
    kind: 'city', dayStartTime: '06:45',
    stops: [
      { name: 'Hotel Kyoto', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel (temprano, para llegar a Kiyomizu antes que los grupos).', transit: 'Bus Kioto City Bus Shijo Karasuma → Kiyomizu-michi, ~20 min.', transitMin: 20 },
      { name: 'Kiyomizu-dera', kind: 'visit', durOverride: 60, note: 'Ir a primera hora, antes de que lleguen los grupos.' },
      { name: 'Sannenzaka', kind: 'visit', note: 'Recorredla antes o después de Kiyomizu-dera: antes las tiendas están cerradas, después hay más ambiente pero también más gente — mucho más tranquila sobre las 19:00-19:30.' },
      { name: 'Ninenzaka', kind: 'visit', note: 'Igual que Sannenzaka: mucho más tranquila sobre las 19:00-19:30.' },
      { name: 'Koyasu-no-to Pagoda', kind: 'visit', durOverride: 20, note: 'Caminad por este sendero para las mejores vistas.' },
      { name: 'Templo Hokan-ji (Pagoda Yasaka)', kind: 'visit', durOverride: 20, note: 'Las calles de alrededor quedan espectaculares de noche.' },
      { name: 'Santuario Yasaka', kind: 'visit', durOverride: 25 },
      { name: 'Gion', kind: 'visit', durOverride: 85, mealAfter: 'lunch' },
      { name: 'Hanamikoji-dori', kind: 'visit', durOverride: 50 },
      { name: 'Gionmachi Minamigawa', kind: 'visit', durOverride: 50 },
      { name: 'Miyakawa-cho Dori', kind: 'visit', durOverride: 50 },
      { name: 'Hanamikoji Street', kind: 'visit', durOverride: 50 },
      { name: 'Santuario Yasui Konpira', kind: 'visit', durOverride: 30 },
      { name: 'Monumentos de piedra y encantos de Pontocho', kind: 'visit', durOverride: 90, note: 'Los farolillos se ven mejor ya de noche — id sobre las 22:00, cuando los restaurantes ya han cerrado y hay mucha menos gente.', mealAfter: 'dinner', transit: 'Paseo de 20 min junto al río Kamo, o autobús directo Kawaramachi → Shijo Karasuma (~10 min).', transitMin: 15 },
      { name: 'Hotel Kyoto', kind: 'info' },
    ],
  },
  {
    date: '2026-11-07', city: 'Kioto', locationLabel: 'Kyoto', title: 'Kinkaku-ji y Arashiyama',
    kind: 'city', dayStartTime: '08:00',
    stops: [
      { name: 'Hotel Kyoto', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.', transit: 'Bus Kioto City Bus Karasuma → Kinkakuji-michi, ~30 min.', transitMin: 30 },
      { name: 'Pabellon Dorado', kind: 'visit', durOverride: 40 },
      { name: 'Ryōan-ji', kind: 'visit', durOverride: 40 },
      { name: 'Ninna-ji', kind: 'visit', durOverride: 40, transit: 'Bus Kioto City Bus Ninnaji-mae → Ichijōji, ~10 min.', transitMin: 12 },
      { name: 'Taishogun Shopping Street - Ichijo Yokai Street', kind: 'visit', durOverride: 20, transit: 'Bus Kioto City Bus o JR Sagano Line Hanazono → Saga-Arashiyama, ~20 min en total.', transitMin: 20 },
      { name: 'Templo Tenryu-ji', kind: 'visit', durOverride: 40 },
      { name: 'Bosque de Bambú de Arashiyama', kind: 'visit', durOverride: 20 },
      { name: 'Arashiyama Yoshimura', kind: 'meal', mealType: 'lunch', durOverride: 45 },
      { name: 'Arashiyama Nakaoshitacho', kind: 'visit', durOverride: 50 },
      { name: 'Arashiyama Monkey Park Iwatayama', kind: 'visit', durOverride: 120 },
      { name: 'Adashino Nenbutsuji Temple', kind: 'visit', durOverride: 70, transit: 'JR Sagano Line Saga-Arashiyama → Kioto Station (~15-20 min) + bus/metro al hotel (~10 min).', transitMin: 30 },
      { name: 'Hotel Kyoto', kind: 'info' },
      { name: 'Sushitetsu', kind: 'meal', mealType: 'dinner', durOverride: 60, note: 'Sugerencia para cenar, cerca del hotel — cambiadlo si preferís otra cosa.' },
      { name: 'Takkyubin: preparar bolsa pequeña (envío a Osaka)', kind: 'info', note: 'Mañana (8 nov) se entrega la maleta grande en el hotel para el takkyubin a Osaka.' },
    ],
  },
  {
    date: '2026-11-08', city: 'Kioto', locationLabel: 'Kyoto', title: 'Fushimi Inari y el Camino del Filósofo (Ginkaku-ji)',
    kind: 'city', dayStartTime: '06:45',
    travelNote: 'Fushimi Inari y Sanjusangen-dō están al sur (cerca de la estación de Kioto); Ginkaku-ji y el Camino del Filósofo están al norte.',
    stops: [
      { name: 'Hotel Kyoto', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno temprano en el hotel (o para llevar) — Fushimi Inari conviene cogerlo nada más abrir.' },
      { name: 'Takkyubin: entregar maleta (envío a Osaka)', kind: 'info', note: 'Destino: Hotel Keihan Tenmabashi Ekimae, Osaka. Entrega prevista: 9 nov.', transit: 'JR Nara Line Kioto/Tōfukuji → Inari, ~5-10 min (+ 10-15 min hasta la estación desde el hotel).', transitMin: 20 },
      { name: 'Fushimi Inari-taisha', kind: 'visit', durOverride: 180, note: 'Ir muy temprano. Subida completa 2-3h; con llegar al mirador Yotsutsuji (~1h ida y vuelta) ya merece la pena.', transit: 'JR Nara Line Inari → Kioto (~5 min) + JR/bus a Sanjūsangen-dō (~10 min), o taxi directo (~15 min).', transitMin: 20 },
      { name: 'Sanjusangendomawari', kind: 'visit', durOverride: 108, mealAfter: 'lunch', transit: 'Bus o taxi hasta Heian Jingū, ~15 min.', transitMin: 15 },
      { name: 'Heian Jingū', kind: 'visit', durOverride: 30, note: 'El jardín trasero (de pago) es un buen contraste tranquilo antes de seguir al Camino del Filósofo.', transit: '15 min andando o en bus a Ginkaku-ji.', transitMin: 15 },
      { name: 'Ginkaku-ji', kind: 'visit', durOverride: 60 },
      { name: 'Mirokuin Temple', kind: 'visit', durOverride: 15 },
      { name: 'Hōnenin Temple', kind: 'visit', durOverride: 30 },
      { name: 'Anraku-ji Temple', kind: 'visit', durOverride: 20, note: 'Como Reikan-ji, suele abrir solo unas semanas al año — comprobad fechas antes de ir.' },
      { name: 'Reikan-ji', kind: 'visit', durOverride: 20, note: 'Abre solo unas semanas al año, a menudo coincidiendo con el otoño — comprobad fechas antes de ir.' },
      { name: 'Tetsugaku No Michi', kind: 'visit', durOverride: 10 },
      { name: 'Santuario Otoyo', kind: 'visit', durOverride: 25 },
      { name: 'Kumano Nyakuōji Shrine', kind: 'visit', durOverride: 15 },
      { name: 'Templo Eikando', kind: 'visit', durOverride: 45 },
      { name: 'Nanzen-ji', kind: 'visit', durOverride: 45, transit: 'Bus Kioto City Bus Nanzenji-michi → Shijo Karasuma, ~20-25 min.', transitMin: 25 },
      { name: 'Hotel Kyoto', kind: 'info', mealAfter: 'dinner' },
    ],
  },
  {
    date: '2026-11-09', city: 'Kioto', locationLabel: 'Kyoto', title: 'Daigo-ji, Uji y Nara → Osaka',
    kind: 'travel', dayStartTime: '08:05',
    travelNote: 'Las maletas grandes ya van camino de Osaka por takkyubin (enviadas ayer) — hoy viajáis solo con la bolsa de mano. Desvío a Daigo-ji (metro Tozai Line) antes de coger la JR Nara Line hacia el sur — añade ~45 min de trenes respecto a ir directos, pero de camino hacia Nara igualmente se para en Uji (Byōdō-in). Por la tarde, Kintetsu Nara Line directo hasta Osaka-Namba (~35-40 min) — no hace falta volver a Kioto.',
    stops: [
      { name: 'Hotel Kyoto', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel. Solo lleváis la bolsa de mano — las maletas grandes ya van camino de Osaka.', transit: 'Metro Tozai Line (vía Karasuma-Oike) a Daigo, ~25 min en total.', transitMin: 25 },
      {
        name: 'Daigo-ji', kind: 'visit', durOverride: 45,
        note: 'Añade ~45 min de trenes respecto a ir directos a Uji/Nara, pero merece la pena. No os perdáis la Sala Bentendo.',
        transit: 'Metro Tozai Line Daigo → Kioto (~25 min) + JR Nara Line a Uji, ~20 min.', transitMin: 45,
      },
      {
        name: 'Byōdō-in', kind: 'visit', durOverride: 40,
        transit: 'JR Nara Line Uji → JR Nara (~25 min, el único tren directo desde Uji) + bus Nara Kotsu al parque (~10-15 min). Para el regreso a Osaka usaréis la estación Kintetsu-Nara, más cerca del parque.', transitMin: 40,
      },
      { name: 'Parque de Nara', kind: 'visit', durOverride: 15 },
      { name: 'Tōdai-ji', kind: 'visit', durOverride: 45 },
      { name: 'Nigatsu-dō', kind: 'visit', durOverride: 25, note: 'Buen sitio para descansar un rato — hay té gratis.' },
      { name: 'Santuario Kasuga Taisha', kind: 'visit', durOverride: 30, transit: 'Bus Nara Kotsu hasta Kintetsu-Nara (~8 min, con espera), o 25-30 min andando por el parque.', transitMin: 18 },
      { name: 'Kamaiki (Udon)', kind: 'meal', mealType: 'lunch', durOverride: 45, note: 'Abre 11:00-15:00 y 17:00-21:00 y suele haber cola al mediodía — llegad antes de las 14:30. Solo efectivo.' },
      { name: 'Nakatanidō', kind: 'visit', durOverride: 15, note: 'Probad el yomogi mochi recién hecho mientras lo golpean.' },
      { name: 'Higashimuki Shopping Street', kind: 'visit', durOverride: 20, note: 'Última compra o recuerdo antes del tren — la estación Kintetsu-Nara está a 3 min andando.', transit: 'Andando o en bus Nara Kotsu hasta la base del monte (~25 min).', transitMin: 25 },
      {
        name: 'Monte Wakakusa', kind: 'visit', durOverride: 70, optional: true,
        note: 'Opcional — empezad antes de las 16:00 y comprobad que siga abierto (suele cerrar hacia las 17:00). Si os lo saltáis, id directos de Higashimuki a la estación Kintetsu-Nara y llegaréis ~2h antes a Osaka.',
        transit: 'Bajando, a pie o en bus hasta la estación Kintetsu-Nara (~25 min).', transitMin: 25,
      },
      { name: 'Estación Kintetsu-Nara', kind: 'info', transit: 'Kintetsu Nara Line directo Kintetsu-Nara → Osaka-Namba (~40 min, ¥680, sin trasbordos) + metro hasta Tenmabashi (~15-20 min).', transitMin: 55 },
      { name: 'Hotel Osaka', kind: 'info', note: 'Check-in en el Hotel Keihan Tenmabashi Ekimae — las maletas grandes, enviadas ayer por takkyubin desde Kioto, ya deberían estar esperando. Tarde libre para descansar tras el viaje — Takimikoji, junto a Umeda, es una opción para cenar (también pasáis cerca el último día).' },
    ],
  },
  // ---------------- OSAKA ----------------
  {
    date: '2026-11-10', city: 'Osaka', locationLabel: 'Osaka', title: 'Castillo, Shinsaibashi, Dōtonbori y Umeda Sky',
    kind: 'city', dayStartTime: '08:00',
    travelNote: 'Día completo en Osaka, sin prisas — primera mañana entera en la ciudad tras el viaje de ayer, mejor con calma que con una excursión larga fuera.',
    stops: [
      { name: 'Hotel Osaka', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.' },
      { name: 'Castillo Osaka', kind: 'visit', durOverride: 130, note: 'Horario 9:00-17:00. El exterior es más espectacular que el museo interior.', transit: 'Metro Tanimachi Line Osakajōkōen → Tanimachi 9-chōme (~10 min) + 5 min andando a Kuromon Market — o ~50 min andando directo.', transitMin: 20 },
      { name: 'Kuromon Market', kind: 'visit', durOverride: 100, mealAfter: 'lunch', note: 'Abierto de lunes a sábado, de 8:00 a 18:00. Buen sitio para sushi y sashimi frescos.' },
      { name: 'Shinsaibashisuji', kind: 'visit', durOverride: 30 },
      { name: 'America-mura', kind: 'visit', durOverride: 30 },
      { name: 'Sennichimae', kind: 'visit', durOverride: 20 },
      { name: 'Ebisu Bashi-Suji', kind: 'visit', durOverride: 20 },
      { name: 'Dōtonbori', kind: 'visit', durOverride: 60, note: 'Restaurantes recomendados: Houzenji Sanpei y Mizuno. Podéis seguir el canal hasta la tienda Don Quijote, reconocible por la noria en su fachada.' },
      { name: 'Don Quijote Dotonbori Midosuji', kind: 'visit', durOverride: 20 },
      { name: 'Hozenji Yokocho', kind: 'visit', durOverride: 20 },
      { name: 'Nipponbashi', kind: 'visit', durOverride: 30, transit: 'Metro Midosuji Line Namba → Umeda, ~10 min — o ~90 min andando.', transitMin: 10 },
      { name: 'Umeda Sky Building (osaka)', kind: 'visit', durOverride: 45, note: 'Horario 10:00-22:30.' },
      { name: 'Takimikoji', kind: 'meal', mealType: 'dinner', durOverride: 30, optional: true, note: 'Opcional, justo al lado del Umeda Sky Building.' },
      { name: 'Hotel Osaka', kind: 'info' },
    ],
  },
  {
    date: '2026-11-11', city: 'Osaka', locationLabel: 'Osaka', title: 'Excursión a Hiroshima y Miyajima',
    kind: 'daytrip', dayStartTime: '06:00',
    optional: true, altGroup: 'day11', altLabel: 'A',
    altNote: 'Elegid <b>11A (Hiroshima y Miyajima)</b> o <b>11B (Universal Studios)</b> — decidimos no ir finalmente a Universal, así que 11A es el plan real; 11B se deja tal cual por si cambiáis de idea.',
    travelNote: 'Salida muy temprano: Shinkansen Sanyo (Nozomi/Sakura) Shin-Osaka → Hiroshima, ~1h20-1h35. Es un día largo — salir con el primer tren que podáis y volved directos al hotel a descansar.',
    stops: [
      { name: 'Hotel Osaka', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno rápido o para llevar — a esta hora muchos hoteles aún no lo sirven, confirmad el horario la noche anterior.', transit: 'Metro a Shin-Osaka (~15-20 min) + Shinkansen Sanyo a Hiroshima (~1h20-1h35).', transitMin: 110 },
      { name: 'Hiroshima', kind: 'visit', durOverride: 0 },
      { name: 'Parque Memorial de la Paz de Hiroshima', kind: 'visit', durOverride: 60, transit: 'Tranvía Hiroden Genbaku Dome-mae → Kamiyachō, ~5 min + 5 min andando.', transitMin: 12 },
      { name: 'Castillo de Hiroshima', kind: 'visit', durOverride: 45, transit: '10 min andando al Jardín Shukkeien.', transitMin: 10 },
      { name: 'Jardín Shukkeien', kind: 'visit', durOverride: 30, note: 'Muy cerca del hipocentro de la explosión — sirvió de refugio a los supervivientes tras la bomba atómica.', transit: 'Tranvía Hiroden desde la parada más cercana → Hatchōbori, ~10 min en total.', transitMin: 15 },
      { name: 'Okonomimura', kind: 'visit', durOverride: 45 },
      { name: 'Hondori Shopping Street', kind: 'visit', durOverride: 20, transit: 'JR Sanyo Line Hiroshima → Miyajimaguchi (~25 min) + ferry JR/Miyajima Matsudai (~10 min).', transitMin: 40 },
      { name: 'Miyahima', kind: 'visit', durOverride: 0, note: 'El paseo por la orilla hasta el torii es parte del atractivo — se recorre andando.' },
      { name: 'Torii Flotante del Santuario Itsukushima', kind: 'visit', durOverride: 30 },
      { name: 'Santuario Itsukushima', kind: 'visit', durOverride: 30 },
      { name: 'Santuario Toyokuni (Senjokaku)', kind: 'visit', durOverride: 20, note: 'La pagoda de cinco pisos de al lado es del mismo conjunto.' },
      { name: 'Calle Comercial Miyajima Omotesando', kind: 'visit', durOverride: 30, note: 'La mayoría de tiendas cierran sobre las 18:00.' },
      { name: 'Parque Momijidani', kind: 'visit', durOverride: 20, note: 'A principios de noviembre es buena época para verlos en pleno color.', transit: 'Bus gratuito a la estación del ropeway + telesférico Miyajima, ~15 min en total.', transitMin: 20 },
      { name: 'Monte Misen', kind: 'visit', durOverride: 90, transit: 'Teleférico de bajada (~15 min) + ferry a Miyajimaguchi (~10 min) + JR a Hiroshima (~25 min) + Shinkansen Sanyo a Shin-Osaka (~1h20-1h35) + metro al hotel (~20 min).', transitMin: 160 },
      { name: 'Hotel Osaka', kind: 'info' },
    ],
  },
  {
    date: '2026-11-11', city: 'Osaka', locationLabel: 'Osaka', title: 'Universal Studios Japan',
    kind: 'daytrip', dayStartTime: '08:00',
    optional: true, altGroup: 'day11', altLabel: 'B',
    altNote: 'Elegid <b>11B (Universal Studios)</b> o <b>11A (Hiroshima y Miyajima)</b> — decidimos no ir finalmente a Universal, así que este día se queda como alternativa por si cambiáis de idea; el plan real es 11A.',
    travelNote: 'JR Kanjo Line o Nankai/metro directo Namba/Osaka → Universal City (~20-25 min). Recomendado ir entre semana con pase express para 4 atracciones — planificad las atracciones en la app antes de entrar.',
    stops: [
      { name: 'Hotel Osaka', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.', transit: 'JR Osaka Loop Line Temmabashi/Osaka → Nishikujo (~15 min) + JR Yumesaki Line a Universal City (~5 min).', transitMin: 25 },
      { name: 'Universal Studios Japan', kind: 'visit', durOverride: 480, note: 'Mejor entre semana. Descargad la app para planificar las atracciones. Entrada normal ~48€, pase express de 4 atracciones ~101€. Comida dentro del parque.', transit: 'JR Yumesaki Line Universal City → Nishikujo (~4 min) + JR Osaka Loop Line a Osaka/Temmabashi (~20 min).', transitMin: 30 },
      { name: 'Hotel Osaka', kind: 'info' },
    ],
  },
  {
    date: '2026-11-12', city: 'Osaka', locationLabel: 'Osaka', title: 'Shinsekai → Aeropuerto',
    kind: 'city', dayStartTime: '10:00',
    travelNote: 'Vuelo OSAKA KANSAI 23:20 → Singapur 05:00 (+1) — día deliberadamente ligero (el resto de Osaka ya se ve con calma el 10 nov): una mañana en Shinsekai y toda la tarde libre en el hotel (maletas, descanso, última compra) antes de salir hacia el aeropuerto sobre las 19:30-20:00, con margen de sobra para el Tax Free y el control de pasaportes.',
    stops: [
      { name: 'Hotel Osaka', kind: 'meal', mealType: 'breakfast', durOverride: 30, note: 'Desayuno en el hotel.', transit: 'Metro Tanimachi/Midosuji hasta Dōbutsuen-mae (Shinsekai), ~20-25 min — o ~70 min andando.', transitMin: 25 },
      { name: 'Tower Slider (Tsutenkaku)', kind: 'visit', durOverride: 130, note: 'Con calma: mirador, la bajada en el tobogán y un paseo por Janjan Yokocho.' },
      { name: 'Magic Cafe & Bar Shinsekai', kind: 'meal', mealType: 'lunch', durOverride: 45, transit: 'Metro Midosuji/Tanimachi de vuelta al hotel, ~20-25 min — o ~75 min andando.', transitMin: 25 },
      { name: 'Hotel Osaka', kind: 'visit', durOverride: 300, note: 'Tarde libre — maletas con calma, descanso, alguna compra de última hora. Salid hacia el aeropuerto sobre las 19:30-20:00.', transit: 'Metro/tren a la estación + Nankai "Rapi:t" o JR Kansai Airport Line a Kansai Airport (~40-45 min).', transitMin: 55 },
      { name: 'Aeropuerto Internacional de Kansai', kind: 'info', note: 'Vuelo de vuelta: Osaka Kansai → Singapur, 12 nov 23:20 → 05:00 (+1).' },
    ],
  },
];

// Envíos de takkyubin (maleta grande) — toda la info necesaria para gestionarlo en recepción del hotel de origen.
const takkyubin = [
  {
    title: 'Envío 1: Tokio → Kioto',
    note: 'Así se hacen Kanazawa, Shirakawa-go y Takayama (2-5 nov) solo con la mochila.',
    origin: {
      label: 'Entregar el',
      date: '2 nov 2026',
      hotel: 'Hotel Tobu Levant Tokyo',
      address: '1-2-2 Kinshi, Sumida-ku, Tokio 130-0013',
      addressJp: '〒130-0013 東京都墨田区錦糸1-2-2',
      phone: '+81 3-5611-5511',
    },
    destination: {
      label: 'Entrega prevista el',
      date: '5 nov 2026',
      hotel: 'Hotel Resol Kyoto Shijo Muromachi',
      address: '554 Sanno-cho, Muromachi-dori Takatsuji-agaru, Shimogyo-ku, Kioto 600-8424',
      addressJp: '〒600-8424 京都府京都市下京区室町通高辻上ル山王町554',
      phone: '+81 75-365-9269',
    },
  },
  {
    title: 'Envío 2: Kioto → Osaka',
    note: 'Así se hace la excursión a Nara y el traslado a Osaka (9 nov) sin cargar con la maleta grande.',
    origin: {
      label: 'Entregar el',
      date: '8 nov 2026',
      hotel: 'Hotel Resol Kyoto Shijo Muromachi',
      address: '554 Sanno-cho, Muromachi-dori Takatsuji-agaru, Shimogyo-ku, Kioto 600-8424',
      addressJp: '〒600-8424 京都府京都市下京区室町通高辻上ル山王町554',
      phone: '+81 75-365-9269',
    },
    destination: {
      label: 'Entrega prevista el',
      date: '9 nov 2026',
      hotel: 'Hotel Keihan Tenmabashi Ekimae',
      address: '2-13 Tenmabashikyomachi, Chuo-ku, Osaka 540-0032',
      addressJp: '〒540-0032 大阪府大阪市中央区天満橋京町2-13',
      phone: '+81 6-6946-0321',
    },
  },
];

// Lugares del KMZ que no se han metido en ningún día (opcionales / por si sobra tiempo)
const extras = {
  Tokio: ['Chōfu', 'Jardín Botánico Jindaiji', '大正寺 山門(竜宮門)', 'Shibamata', 'Shibamata Taishakuten', 'Yamanote Line', 'SUSHI Gompachi Nishi-Azabu', 'Mount Fuji Fujinomiya 5th Station', 'Tokyo Skytree'],
  'Kanazawa-Takayama': ['Castillo de Nagoya'],
  Kioto: [
    "Philosopher's Path (Tetsugaku no Michi), North End", 'Shugakuin Imperial Villa',
  ],
  Osaka: [
    'Sumiyoshi Taisha', 'Templo Katsuo-ji',
    'Teleférico de Miyajima',
  ],
};

// Excursiones alternativas (no asignadas a un día fijo, para intercambiar por otra si sobra tiempo)
const altDayTrips = [
  {
    id: 'tsuruga', title: 'Tsuruga, Hikone y Fukui (alternativa, desde Kioto)',
    note: 'Kioto → Maibara (JR Biwako Line, ~50 min) → Castillo Hikone (JR ~10 min) → Tsuruga (limited express Hokuriku, ~30-40 min desde Maibara) → Fukui (JR ~20 min más). Los tres en un día realista solo si vais justos de tiempo en cada parada; con calma, recomendado quedarse en Hikone + Tsuruga.',
    stops: ['Tsuruga', 'Castillo Hikone', 'Fukui'],
  },
];

module.exports = { CITY_COLORS, days, extras, altDayTrips, manualPlaces, manualFood, takkyubin };
